CREATE DATABASE IF NOT EXISTS wordpress_db;
CREATE USER IF NOT EXISTS 'admin'@'%' IDENTIFIED BY 'admin123';
GRANT REPLICATION SLAVE ON *.* TO 'admin'@'%';
GRANT ALL PRIVILEGES ON `wordpress_db`.* TO 'admin'@'%';
FLUSH PRIVILEGES;
